# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/git/circuit_ETC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/git/circuit_ETC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/git/circuit_ETC/CMakeFiles /home/pi/git/circuit_ETC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/git/circuit_ETC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MicroGridRTU

# Build rule for target.
MicroGridRTU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MicroGridRTU
.PHONY : MicroGridRTU

# fast build rule for target.
MicroGridRTU/fast:
	$(MAKE) -f CMakeFiles/MicroGridRTU.dir/build.make CMakeFiles/MicroGridRTU.dir/build
.PHONY : MicroGridRTU/fast

MicroGridIOHandler.o: MicroGridIOHandler.cpp.o
.PHONY : MicroGridIOHandler.o

# target to build an object file
MicroGridIOHandler.cpp.o:
	$(MAKE) -f CMakeFiles/MicroGridRTU.dir/build.make CMakeFiles/MicroGridRTU.dir/MicroGridIOHandler.cpp.o
.PHONY : MicroGridIOHandler.cpp.o

MicroGridIOHandler.i: MicroGridIOHandler.cpp.i
.PHONY : MicroGridIOHandler.i

# target to preprocess a source file
MicroGridIOHandler.cpp.i:
	$(MAKE) -f CMakeFiles/MicroGridRTU.dir/build.make CMakeFiles/MicroGridRTU.dir/MicroGridIOHandler.cpp.i
.PHONY : MicroGridIOHandler.cpp.i

MicroGridIOHandler.s: MicroGridIOHandler.cpp.s
.PHONY : MicroGridIOHandler.s

# target to generate assembly for a file
MicroGridIOHandler.cpp.s:
	$(MAKE) -f CMakeFiles/MicroGridRTU.dir/build.make CMakeFiles/MicroGridRTU.dir/MicroGridIOHandler.cpp.s
.PHONY : MicroGridIOHandler.cpp.s

MicroGridRTU.o: MicroGridRTU.cpp.o
.PHONY : MicroGridRTU.o

# target to build an object file
MicroGridRTU.cpp.o:
	$(MAKE) -f CMakeFiles/MicroGridRTU.dir/build.make CMakeFiles/MicroGridRTU.dir/MicroGridRTU.cpp.o
.PHONY : MicroGridRTU.cpp.o

MicroGridRTU.i: MicroGridRTU.cpp.i
.PHONY : MicroGridRTU.i

# target to preprocess a source file
MicroGridRTU.cpp.i:
	$(MAKE) -f CMakeFiles/MicroGridRTU.dir/build.make CMakeFiles/MicroGridRTU.dir/MicroGridRTU.cpp.i
.PHONY : MicroGridRTU.cpp.i

MicroGridRTU.s: MicroGridRTU.cpp.s
.PHONY : MicroGridRTU.s

# target to generate assembly for a file
MicroGridRTU.cpp.s:
	$(MAKE) -f CMakeFiles/MicroGridRTU.dir/build.make CMakeFiles/MicroGridRTU.dir/MicroGridRTU.cpp.s
.PHONY : MicroGridRTU.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... MicroGridRTU"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MicroGridIOHandler.o"
	@echo "... MicroGridIOHandler.i"
	@echo "... MicroGridIOHandler.s"
	@echo "... MicroGridRTU.o"
	@echo "... MicroGridRTU.i"
	@echo "... MicroGridRTU.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

